import type { Metadata } from "next";
import './globals.css';
import { raleway } from './fonts'; // Changed: Using our Raleway font loader


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable}`}> {/* Changed: Added Raleway variable */}
      <body className="antialiased"> {/* Changed: Removed Geist variables */}
        {children}
      </body>
    </html>
  );
}